# FROM python:3.12-slim

# # Встановлюємо системні залежності для GDAL, GEOS, PostGIS
# RUN apt-get update && apt-get install -y \
#     binutils \
#     libproj-dev \
#     gdal-bin \
#     libgdal-dev \
#     python3-gdal \
#     && rm -rf /var/lib/apt/lists/*

# # Встановлюємо змінну оточення для GDAL
# ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
# ENV C_INCLUDE_PATH=/usr/include/gdal

# WORKDIR /app

# COPY backend/requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# COPY backend/ .

# # Створюємо директорію для медіафайлів
# RUN mkdir -p /app/media

# # Відкриваємо порт 8000
# EXPOSE 8000

# # Запускаємо міграції та сервер
# CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

# залежності для кубернетеса

FROM python:3.12-slim-bookworm

# Вимикаємо перевірку дати (потрібно для Minikube, де час може відставати)
RUN echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99ignore-date && \
    echo 'Acquire::Check-Date "false";' >> /etc/apt/apt.conf.d/99ignore-date

# Встановлюємо необхідні бібліотеки
RUN apt-get update && apt-get install -y \
    binutils \
    libproj-dev \
    gdal-bin \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

RUN mkdir -p /app/media

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]